# Generated by Django 5.2.4 on 2026-07-08 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("step", models.IntegerField()),
                ("action", models.CharField(max_length=32)),
                ("tool", models.CharField(blank=True, max_length=32, null=True)),
                ("input", models.JSONField(blank=True, null=True)),
                ("output", models.JSONField(blank=True, null=True)),
                ("reasoning", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "agent_trace",
                "ordering": ["run_id", "step"],
            },
        ),
    ]
