# Generated by Django 5.2.4 on 2025-08-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CentralPolicy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("type", models.CharField(max_length=100)),
                ("publish_time", models.DateTimeField()),
                ("source_url", models.URLField(blank=True, max_length=1000)),
            ],
            options={
                "db_table": "central_policies",
                "ordering": ["-publish_time"],
            },
        ),
        migrations.CreateModel(
            name="LocalPolicy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("province", models.CharField(max_length=100)),
                ("publish_time", models.DateTimeField()),
                ("source_url", models.URLField(blank=True, max_length=1000)),
            ],
            options={
                "db_table": "local_policies",
                "ordering": ["-publish_time"],
            },
        ),
    ]
