# Generated by Django 5.2.4 on 2026-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="centralpolicy",
            name="crawled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="采集时间"),
        ),
        migrations.AddField(
            model_name="localpolicy",
            name="crawled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="采集时间"),
        ),
    ]
